// <auto-generated />
namespace StoryTeller.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MalachiTitleFieldInFavorites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MalachiTitleFieldInFavorites));
        
        string IMigrationMetadata.Id
        {
            get { return "201808111613488_MalachiTitleFieldInFavorites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
