// <auto-generated />
namespace StoryTeller.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Malachi3NewTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Malachi3NewTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081554287_Malachi3NewTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
